### ISSUE TITLE
Tests not working properly

### ISSUE THREAD

**Issue by rivermont** [rivermont/spidy#27]
From [`tests.py`](https://github.com/rivermont/spidy/blob/master/tests.py).

  - `test_make_words_given_string`
    - Fails with `AttributeError: 'str' object has no attribute 'text'`
    - `make_words` needs to be passed a `requests.models.Response` object in order to extract to text properly, however I'm not sure there is a way to simulate that. Something like `StringIO` for files...?
    - I feel like getting a page and passing it would take too long to be an acceptable test, but I could be wrong. Would take ~5 seconds.
  - `test_mime_lookup_given_unknown_type`
    - Fails with `crawler.HeaderError: Unknown MIME type: this_mime_doesn't_exist`
    - It should be caught with the [`assertRaises`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises) statement.

**Comment by brandonmburroughs** [comment]
I'm working on this now.

**Comment by rivermont** [comment]
I'll leave this open for now so we can have a couple different approaches.
