### ISSUE TITLE
Multiple HTTP Threads

### ISSUE THREAD

**Issue by rivermont** [rivermont/spidy#29]
Crawling would go much faster connecting to multiple pages at once.

Possible Problems:

* Crawling same page twice
* Corruption of save files if reading/writing at different places at the same time.

These should be solvable using [mutexes](https://stackoverflow.com/questions/3310049/proper-use-of-mutexes-in-python).

**Comment by Hrily** [comment]
I would like to take this up...

**Comment by mohamed-aziz** [comment]
I don't think you want to use mutual exclusion here, why not just use a global task queue you can pop from the queue from each thread and then enqueue new urls, at least this is what should be used by default.

**Comment by Hrily** [comment]
@mohamed-aziz 
Unless the enqueue and dequeue operations are atomic, the system will fail if mutex is not used.
Think of the situation when two threads are dequeuing simultaneously. Thread 1 checks queue and knows queue isn't empty. Meanwhile the other thread checks and dequeues leading to an empty queue.
Thus Thread 1 still thinks queue has urls but it's does not.
This will lead to inconsistency.

So solution is to make enqueue and dequeue atomic, which again requires mutex.

**Comment by mohamed-aziz** [comment]
@Hrily yes sure I just meant we don't need to implement locks since Queue  (https://docs.python.org/2/library/queue.html#module-Queue) is already thread safe (it uses mutex at a lower level) most of the work is done for us.

**Comment by Hrily** [comment]
@mohamed-aziz 
Thanks for the info... :)

@rivermont 
Should we use queue instead if list for `TODO` and `DONE`?

**Comment by rivermont** [comment]
Yeah, whatever works. I hadn't looked into it very far.

**Comment by rivermont** [comment]
The multithreading is real.
