### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by petermbenjamin** [rivermont/spidy#32]
I've been looking for a decent command-line web crawler for some time and came across this project. It seems very promising.

I have been working on getting this project working in a docker container. 

Would you be interested in my contributing the dockerfile back to this project for anyone else who might be interested in the same?

**Comment by rivermont** [comment]
Sure! I haven't used Docker before but it looks like a great resource to have.

**Comment by petermbenjamin** [comment]
Yeah, Docker is a great resource to have. It helps with **development** and **deployment** of applications.

### Development
I have long replaced my local development environments with Docker containers, which eliminates the need for me to muck around locally and struggle with different versions of libraries/runtimes/binaries ...etc.

Need to do Python 3.6 development? `docker run --rm -it -v /local/repo:/path/inside/container python bash`
Need to do Ruby development? `docker run --rm -it -v /local/repo:/path/inside/container ruby bash`
And so on...

### Deployment
On your local machine:
- Build the image: `docker build -t <IMAGE_NAME> /path/to/Dockerfile`
- Push the image to the registry of choice: `docker push <IMAGE_NAME>`
On the server:
- Pull down the image and run it as a container: `docker run [OPTIONS] <IMAGE_NAME>`


Call me a fanboy, I haven't experienced such portability, consistent cross-platform development (e.g. OSX, Linux, Windows), and ease of deployment before using Docker.
