### ISSUE TITLE
Issue and PR Templates

### ISSUE THREAD

**Issue by rivermont** [rivermont/spidy#35]
It would be a good idea to have templates for these. I have created [`TEMPLATES.md`](https://github.com/rivermont/spidy/blob/master/TEMPLATES.md) as a start but would love some more input.

I looked [here](https://github.com/stevemao/github-issue-templates) to get started.

**Comment by iharsh234** [comment]
I love to take this, Don't you think i should be better to have 2 different markdown files , like `ISSUE.md` and `PR.md`
