### ISSUE TITLE
spidy Logo Design

### ISSUE THREAD

**Issue by rivermont** [rivermont/spidy#36]
Possibly something reminiscent of the [Python logo](https://www.google.com/search?q=python+logo&tbm=isch), but not obvious. Other than that, anything would be great.

**Comment by AK-007** [comment]
Do you want the logo to contain Single Letter or spider.Any specific colours you want the logo to have?

**Comment by rivermont** [comment]
@AK-007 Whatever works. I don't have any specific ideas in mind, except to stay away from other people's logos.

**Comment by Cutwell** [comment]
I've got a couple ideas, I'll make a PR and you can give your op
