### ISSUE TITLE
PyPI Package

### ISSUE THREAD

**Issue by rivermont** [rivermont/spidy#37]
It would be great to have spidy on the Package Index (the new one); installing would be only one command. I have tried to get it going, my efforts can be found on the `pypi-dev` branch.

There are some problems with imports, file saving, tests, etc.

While I would like to be the owner/maintainer of the package, some help getting it started would greatly appreciated.

**Comment by DeKaN** [comment]
I can help with it

**Comment by rivermont** [comment]
Finally got it working with fa623db.
