### ISSUE TITLE
HEAD Request uses default Requests headers

### ISSUE THREAD

**Issue by rivermont** [rivermont/spidy#48]
The initial HEAD request sent to get the document's size is not using the set HTTP headers that the GET request is. Should be a simple fix.

**Comment by ayushkalani** [comment]
I'm interested in doing it

**Comment by ayushkalani** [comment]
Can you please tell me the function and the file where to make these changes and please elaborate

**Comment by rivermont** [comment]
See the [`crawl()` function in `crawler.py`](https://github.com/rivermont/spidy/blob/master/spidy/crawler.py#L95).

**Comment by Double-A-92** [comment]
@ayushkalani In https://github.com/rivermont/spidy/blob/master/spidy/crawler.py compare line 100 with line 107.

**Comment by AwesomeMarioFan** [comment]
I've opened a pull request for this here: https://github.com/rivermont/spidy/issues/48

**Comment by mohamed-aziz** [comment]
Ah fine, I'm a little late I'll work on something else.
