### ISSUE TITLE
No error raised for incorrect input

### ISSUE THREAD

**Issue by rivermont** [rivermont/spidy#57]
## Checklist

- [X] Same issue has not been opened before.

## Expected Behavior
Raise an `InputError` and *then* stop the crawler.

## Actual Behavior
No output, just exits straight to console.

## Steps to Reproduce the Problem

  1. Run crawler
  2. Choose 'No' to config file.
  3. Type incorrect type of input 

## Specifications

  - Crawler Version: 1.6.2
  - Platform: Ubuntu (16.04 LTS)
  - Python Version: 3.5.2
  - Dependency Versions: Latest

**Comment by rivergillis** [comment]
I can start working on this.

**Comment by rivergillis** [comment]
A `SyntaxError` is already raised from the incorrect response via `handle_invalid_input()`, should the `InputError` replace this?

**Comment by rivermont** [comment]
@rivergillis Sure! That'd be great, thanks.

**Comment by rivermont** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[#57] No error raised for incorrect input](https://trello.com/c/6fYVBToh/1-57-no-error-raised-for-incorrect-input)

**Comment by rivermont** [comment]
So the problem is that `SyntaxError` is raised in `handle_invalid_input`, it's caught by the blanket `except Exception:` line at [crawler.py#L1189](https://github.com/rivermont/spidy/blob/master/spidy/crawler.py#L1189) which is a problem.

Instead of changing the error that is raised, I'm just going to have the input loop until user gives an accepted input. No need to make them go through all the settings if they mistype on the last entry.
