### ISSUE TITLE
Write comparison of spidy and similar projects

### ISSUE THREAD

**Issue by rivermont** [rivermont/spidy#64]
I have been asked multiple times what makes Spidy different from similar projects like [Scrapy](https://scrapy.org/) and [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/). There is [a section](https://github.com/rivermont/spidy#why-its-different) in the README, but it doesn't directly address other projects.

**Comment by visin** [comment]
I'd like to write this :)
