### ISSUE TITLE
GitHub Release last in 2017?

### ISSUE THREAD

**Issue by jzabroski** [rivermont/spidy#80]
Can you please use GitHub Releases so I can Unwatch issues and only follow via Watch-> Custom->Releases.

**Comment by rivermont** [comment]
The last Github Release was in 2017 because the last development on the project was in 2017. You can go ahead and change your follow settings; if more development happens I'll be sure to use the Release feature (currently considering a rewrite).

**Comment by jzabroski** [comment]
Thank you - sorry about that.  Was trying a bunch of spidering approaches earlier in the year.
